install:
  - ps: Install-Product node 6.9 
  - cd textlint && npm run install:all

before_build:
  - cd textlint && npm run lint

build_script:
  - cd textlint && npm run compile

test_script:
  - cd test && npm install
  - cd textlint && npm test

cache:
  - textlint\.vscode-test
