environment:
  CI: true

install:
  - cd textlint && npm run install:all

before_build:
  - cd textlint && npm run lint

build_script:
  - cd textlint && npm run compile

test_script:
  - cd textlint && npm test

cache:
  - textlint\.vscode-test
