strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows2016:
      imageName: 'vs2017-win2016'
pool:
  vmImage: $(imageName)
  demands: npm
steps:
  - script: 'git config --global core.autocrlf input'
    displayName: 'config CRLF'
  - checkout: self
  - task: NodeTool@0
    displayName: 'Use Node 8.x'
    inputs:
      versionSpec: 8.x
  - script: 'cd textlint && rm package-lock.json'
    displayName: 'Remove package-lock.json for error'
  - script: 'cd textlint && npm install'
    displayName: 'Install client dependencies'
  - script: 'cd textlint-server && npm install'
    displayName: 'Install server dependencies'
  - script: 'cd test && npm install'
    displayName: 'Install test dependencies'
  - script: 'cd textlint && npm run compile'
    displayName: 'Compile'
  - script: 'cd textlint && npm test'
    displayName: 'run tests'
