jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
      demands: npm
    steps:
      - script: 'git config --global core.autocrlf input'
        displayName: 'config CRLF'
      - checkout: self
      - template: azure-pipelines/common.yml
      - task: Npm@1
        inputs:
          command: 'custom'
          verbose: true
          customCommand: 'test'
          workingDir: textlint
  - job: Linux
    pool:
      vmImage: 'Ubuntu-16.04'
      demands: npm
    steps:
      - checkout: self
      - script: |
          set -e
          sudo apt-get update
          sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0
          sudo cp azure-pipelines/xvfb.init /etc/init.d/xvfb
          sudo chmod +x /etc/init.d/xvfb
          sudo update-rc.d xvfb defaults
          sudo service xvfb start
      - template: azure-pipelines/common.yml
      - script: |
          cd textlint
          export DISPLAY=:10
          npm test
        displayName: Run tests
  - job: Mac
    pool:
      vmImage: 'macos-10.13'
      demands: npm
    steps:
      - checkout: self
      - template: azure-pipelines/common.yml
      - task: Npm@1
        inputs:
          command: 'custom'
          verbose: true
          customCommand: 'test'
          workingDir: textlint
