name: Publish VS Code extension

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: .tool-versions
      - name: Install dependencies
        run: npm ci
      - name: Package extension
        run: npm run package
      - name: Publish extension
        run: npx vsce publish --packagePath ./packages/textlint/*.vsix --pat ${{ secrets.VSCE_PAT }}
